name: Test

# trigger on a push or a pull_request
on: [push, pull_request]

# 1. Checkout
# 2. npm ci
# 3. npm run test
jobs:
  test:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    strategy:
      fail-fast: true
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - run: npm run test
